from pyteomics.mass import calculate_mass

LYS = "KVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVAWRNRCKGTDVQAWIRGCRL"

BSA = "DTHKSEIAHRFKDLGEEHFKGLVLIAFSQYLQQCPFDEHVKLVNELTEFAKTCVADESHAGCEKSLHTLFGDELCKVASLRETYGDMADCCEKQEPERNECFLSHKDDSPDLPKLKPDPNTLCDEFKADEKKFWGKYLYEIARRHPYFYAPELLYYANKYNGVFQECCQAEDKGACLLPKIETMREKVLTSSARQRLRCASIQKFGERALKAWSVARLSQKFPKAEFVEVTKLVTDLTKVHKECCHGDLLECADDRADLAKYICDNQDTISSKLKECCDKPLLEKSHCIAEVEKDAIPENLPPLTADFAEDKDVCKNYQEAKDAFLGSFLYEYSRRHPEYAVSVLLRLAKEYEATLEECCAKDDPHACYSTVFDKLKHLVDEPQNLIKQNCDQFEKLGEYGFQNALIVRYTRKVPQVSTPTLVEVSRSLGKVGTRCCTKPESERMPCTEDYLSLILNRLCVLHEKTPVSEKVTKCCTESLVNRRPCFSALTPDETYVPKAFDEKLFTFHADICTLPDTEKQIKKQTALVELLKHKPKATEEQLKTVMENFVAFVDKCCAADDKEACFAVEGPKLVVSTQTALA"

MYST = "KKLTKEGAAALCKMKHLADKVAKERSQELKDRTQNFAGYIEFELYRIDYWLEKLNGPKGRKDGYAKLSDSDIEKVKEIFNKAKDGITKQLPEAKKAGEEAGKLHTEVKKAAENARGQDLDDDTAKSTGLYRVLNWYCITKEERHNATPNCDGIQFRKHYLSVNRSAIDCSSTSYEENYDWSANALQVALNSWEDVKPKKLESAGSDKNCNIGQSSESHPCTMTEEWQTPYKETVEKLRELEDAYQRGKKAHDAMLGYANTAYAVNTKVEQEKPLTTGLEVLFQGPSAEPEA"

OVA = "GSIGAASMEFCFDVFKELKVHHANENIFYCPIAIMSALAMVYLGAKDSTRTQINKVVRFDKLPGFGDSIEAQCGTSVNVHSSLRDILNQITKPNDVYSFSLASRLYAEERYPILPEYLQCVKELYRGGLEPINFQTAADQARELINSWVESQTNGIIRNVLQPSSVDSQTAMVLVNAIVFKGLWEKAFKDEDTQAMPFRVTEQESKPVQMMYQIGLFRVASMASEKMKILELPFASGTMSMLVLLPDEVSGLEQLESIINFEKLTEWTSSNVMEERKIKVYLPRMKMEEKYNLTSVLMAMGITDVFSSSANLSGISSAESLKISQAVHAAHAEINEAGREVVGSAEAGVDAASVSEEFRADHPFLFCIKHIATNAVLFFGRCVSP"

LIP = "DDNLVGGMTLDLPSDAPPISLSSSTNSASDGGKVVAATTAQIQEFTKYAGIAATAYCRSVVPGNKWDCVQCQKWVPDGKIITTFTSLLSDTNGYVLRSDKQKTIYLVFRGTNSFRSAITDIVFNFSDYKPVKGAKVHAGFLSSYEQVVNDYFPVVQEQLTAHPTYKVIVTGHSLGGAQALLAGMDLYQREPRLSPKNLSIFTVGGPRVGNPTFAYYVESTGIPFQRTVHKRDIVPHVPPQSFGFLHPGVESWIKSGTSNVQICTSEIETKDCSNSIVPFTSILDHLSYFDINEGSCL"


H2O = calculate_mass(formula="H2O")
H2 = calculate_mass(formula="H2")
OH = calculate_mass(formula="OH")
PROTON = calculate_mass(formula="H")
NH3 = calculate_mass(formula="NH3")
SULPHUR = calculate_mass(formula="S")

LYS_BONDS = [(5, 126), (29, 114), (63, 79), (75, 93)]
LIP_BONDS = [(56, 295), (67, 70), (262, 271)]
OVA_BONDS = [(72, 119)]
BSA_BONDS = [
    (b - 1, e - 1)
    for b, e in [
        (53, 62),
        (75, 91),
        (90, 101),
        (123, 168),
        (167, 176),
        (199, 245),
        (244, 252),
        (264, 278),
        (277, 288),
        (315, 360),
        (359, 368),
        (391, 437),
        (436, 447),
        (460, 476),
        (475, 486),
        (513, 558),
        (557, 566),
    ]
]
